### ISSUE TITLE
pnpm support?

### ISSUE THREAD

**Issue by BlackDahlia313** [timio23/directus-panel-manual-flows#1]
since I install via docker, it would be nice to have this registered with npm so I can install it via commands :)

**Comment by alexsonphoenix** [comment]
Hi team, just want to check if it's available wih pnpm now?

**Comment by timio23** [comment]
published to npm as [directus-extension-panel-manual-flows](https://www.npmjs.com/package/directus-extension-panel-manual-flows). I'm hoping this will make it available in the marketplace
